py_binary(
    name = "basic_tests",
    srcs = ["basic_tests.py"],
    deps = [
        "//experimental/users/danilevy/l2hmc/utils:distributions",
        "//experimental/users/danilevy/l2hmc/utils:func_utils",
        "//experimental/users/danilevy/l2hmc/utils:layers",
        "//experimental/users/danilevy/l2hmc/utils:sampler",
        "//file/colossus/public:cns",
        "//file/localfile",
        "//learning/brain/contrib/slim/examples/mnist:mnist_data_provider",
        "//learning/brain/python/platform:app",
        "//third_party/py/tensorflow:tensorflow_google",
    ],
)
