py_library(
    name = "func_utils",
    srcs = ["func_utils.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//file/colossus/public:cns",
        "//pyglib",
        "//pyglib:gfile",
        "//pyglib/flags",
        "//third_party/py/numpy",
        "//third_party/py/scipy",
        "//third_party/py/sklearn",
        "//third_party/py/tensorflow:tensorflow_google",
    ],
)

py_library(
    name = "distributions",
    srcs = ["distributions.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//file/colossus/public:cns",
        "//pyglib",
        "//pyglib:gfile",
        "//pyglib/flags",
        "//third_party/py/numpy",
        "//third_party/py/scipy",
        "//third_party/py/sklearn",
        "//third_party/py/tensorflow:tensorflow_google",
    ],
)

py_library(
    name = "layers",
    srcs = ["layers.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//file/colossus/public:cns",
        "//pyglib",
        "//pyglib:gfile",
        "//pyglib/flags",
        "//third_party/py/numpy",
        "//third_party/py/scipy",
        "//third_party/py/sklearn",
        "//third_party/py/tensorflow:tensorflow_google",
    ],
)

py_library(
    name = "sampler",
    srcs = ["sampler.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//file/colossus/public:cns",
        "//pyglib",
        "//pyglib:gfile",
        "//pyglib/flags",
        "//third_party/py/numpy",
        "//third_party/py/scipy",
        "//third_party/py/sklearn",
        "//third_party/py/tensorflow:tensorflow_google",
    ],
)
